/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 Component Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Pin_rts.h>
#include <Pin_rts_aliases.h>
#include <Pin_PB.h>
#include <Pin_PB_aliases.h>
#include <Pin_R.h>
#include <Pin_R_aliases.h>
#include <UART.h>
#include <Pin_cts.h>
#include <Pin_cts_aliases.h>
#include <isr_UART.h>
#include <UART_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

